"""Collectors for Superbid Exchange and its SOLD channel.

The category pages are server rendered and include a stable ``__NEXT_DATA__``
payload.  Parsing that payload is both faster and less fragile than browser
automation or CSS class names generated by styled-components.
"""

import json
import math
import os
import re
from datetime import datetime
from html import unescape
from typing import Any, Optional
from urllib.parse import urlencode

from bs4 import BeautifulSoup

from .base import BaseSource, ScrapedProperty, apply_known_stages
from .marketplace import detect_seller, is_non_property_offer, property_type_from_text


BASE_URL = "https://www.superbid.net"
CATEGORY_URL = f"{BASE_URL}/categorias/imoveis/sao-paulo-sp"


def _plain_text(value: str | None) -> str:
    return BeautifulSoup(unescape(value or ""), "html.parser").get_text(" ", strip=True)


def _template_values(product: dict[str, Any]) -> dict[str, str]:
    values: dict[str, str] = {}
    for group in (product.get("template") or {}).get("groups") or []:
        for item in group.get("properties") or []:
            item_id = str(item.get("id") or "").casefold()
            if item_id:
                values[item_id] = str(item.get("value") or "").strip()
    return values


def _float_value(value: object) -> Optional[float]:
    if value in (None, ""):
        return None
    try:
        normalized = str(value).strip().replace("R$", "").replace(" ", "")
        if "," in normalized:
            normalized = normalized.replace(".", "").replace(",", ".")
        return float(normalized)
    except ValueError:
        return None


def _date_value(value: str | None):
    if not value:
        return None


def _declared_stages(text: str) -> list[dict[str, Any]]:
    """Extract the number of praças and prices explicitly declared by a lot."""
    stages = []
    names = {"primeira": ("first", "1ª praça"), "segunda": ("second", "2ª praça"), "terceira": ("third", "3ª praça")}
    pattern = re.compile(
        r"(?:Lance\s+Inicial\s+(?:na|da)\s+)?(Primeira|Segunda|Terceira)\s+Pra[cç]a"
        r".{0,160}?R\$\s*([\d.]+,\d{2})",
        re.IGNORECASE | re.DOTALL,
    )
    for match in pattern.finditer(text or ""):
        stage_key, label = names[match.group(1).casefold()]
        if any(stage["stage"] == stage_key for stage in stages):
            continue
        stages.append({
            "stage": stage_key,
            "label": label,
            "sequence": len(stages) + 1,
            "price": _float_value(match.group(2)),
            "event_at": None,
        })
    return stages


def _declared_current_stage(text: str) -> Optional[str]:
    match = re.search(r"\b([123])\s*[ªa]?\s*(?:pra[cç]a|leil[aã]o)\b", text or "", re.I)
    if not match:
        return None
    return {"1": "first", "2": "second", "3": "third"}[match.group(1)]
    try:
        return datetime.strptime(value, "%Y-%m-%d %H:%M:%S").date()
    except ValueError:
        return None


class _SuperbidMarketplaceSource(BaseSource):
    supports_regions = True
    supports_details = True
    supports_documents = True
    supports_photos = True
    include_sold = False

    def __init__(self, max_pages: Optional[int] = None):
        self.max_pages = max_pages or int(os.getenv("SUPERBID_MAX_PAGES", "8"))
        self.page_size = int(os.getenv("SUPERBID_PAGE_SIZE", "30"))
        self.successful_regions: list[str] = []
        self.failed_regions: list[str] = []

    @staticmethod
    def _offers_from_html(html: str) -> tuple[list[dict[str, Any]], int]:
        soup = BeautifulSoup(html, "html.parser")
        payload = soup.select_one("script#__NEXT_DATA__")
        if not payload or not payload.string:
            raise ValueError("Superbid __NEXT_DATA__ não encontrado")
        data = json.loads(payload.string)
        offers_list = data["props"]["pageProps"]["offersList"]
        return list(offers_list.get("offers") or []), int(offers_list.get("total") or 0)

    def _accept_store(self, offer: dict[str, Any]) -> bool:
        store_name = str((offer.get("store") or {}).get("name") or "").strip().casefold()
        is_sold = store_name == "sold" or "sold" in str((offer.get("manager") or {}).get("name") or "").casefold()
        return is_sold if self.include_sold else not is_sold

    def _normalize_offer(self, offer: dict[str, Any]) -> Optional[ScrapedProperty]:
        product = offer.get("product") or {}
        title = str(product.get("shortDesc") or "").strip()
        description = _plain_text(product.get("detailedDescription") or (offer.get("offerDescription") or {}).get("offerDescription"))
        if not title or is_non_property_offer(f"{title} {description}"):
            return None

        location = product.get("location") or {}
        location_city = str(location.get("city") or "")
        if not re.search(r"\bSão Paulo\s*-\s*SP\b", location_city, re.I):
            return None

        price = offer.get("price")
        detail = offer.get("offerDetail") or {}
        auction_price = float(price or detail.get("currentMinBid") or detail.get("initialBidValue") or 0)
        if auction_price <= 0:
            return None

        template = _template_values(product)
        address = template.get("endereco")
        area = _float_value(template.get("areautil") or template.get("areatotal"))
        if not area:
            area_match = re.search(r"([\d.]+(?:,[\d]+)?)\s*m[²2]", title, re.I)
            area = _float_value(area_match.group(1)) if area_match else None

        neighborhood = None
        if address:
            parts = [part.strip() for part in address.split(",") if part.strip()]
            for part in reversed(parts[:-1]):
                if not re.search(r"^(?:cep\s*)?\d", part, re.I) and "são paulo" not in part.casefold():
                    neighborhood = part
                    break

        gallery = product.get("galleryJson") or []
        photos = [str(photo.get("link")) for photo in gallery if photo.get("link")][:12]
        attachments = product.get("attachments") or []
        edital_url = next((str(item.get("link")) for item in attachments if item.get("link") and item.get("contentType") == "application/pdf"), None)

        auction = offer.get("auction") or {}
        event_pipeline = offer.get("eventPipeline") or auction.get("eventPipeline") or {}
        modality_text = str(auction.get("judicialPracaDescription") or auction.get("modalityDesc") or "")
        modality = "segunda_praca" if re.search(r"\b[23]\s*(?:praça|leilão)", modality_text, re.I) else "leilao_online"
        seller_id = detect_seller(title, description, auction.get("desc"), offer.get("store"))
        status = offer.get("offerStatus") or {}

        prop = ScrapedProperty(
            source_id=self.source_id,
            external_id=str(offer["id"]),
            title=title,
            auction_price=auction_price,
            seller_id=seller_id,
            address=address or title,
            neighborhood=neighborhood,
            city="São Paulo",
            state="SP",
            property_type=property_type_from_text(str((product.get("subCategory") or {}).get("description") or title)),
            area_m2=area,
            description=description or title,
            edital_url=edital_url,
            photos=photos,
            auction_date=_date_value(offer.get("endDate")),
            auction_modality=modality,
            is_occupied=True if re.search(r"\bocupad[oa]\b", f"{title} {description}", re.I) and not re.search(r"\bdesocupad[oa]\b", f"{title} {description}", re.I) else (False if re.search(r"\bdesocupad[oa]\b", f"{title} {description}", re.I) else None),
            useful_area_m2=area,
            raw_data={
                "source_url": f"{BASE_URL}/oferta/{offer['id']}",
                "store": offer.get("store"),
                "auction_id": auction.get("id"),
                "auction_description": auction.get("desc"),
                "event_pipeline": event_pipeline,
                "offer_status": status,
                "seller_evidence": seller_id,
            },
        )
        pipeline_stages = event_pipeline.get("stages") or []
        stages = []
        for index, pipeline_stage in enumerate(pipeline_stages, start=1):
            stage_key = {1: "first", 2: "second", 3: "third"}.get(index, f"stage_{index}")
            stages.append({
                "stage": stage_key,
                "label": f"{index}ª praça",
                "sequence": index,
                "price": _float_value(pipeline_stage.get("initialBidValue")),
                "event_at": pipeline_stage.get("endDate"),
            })
        if not stages:
            stages = _declared_stages(description)
        if stages:
            pipeline_current = event_pipeline.get("currentStage")
            current_stage = (
                {1: "first", 2: "second", 3: "third"}.get(int(pipeline_current))
                if str(pipeline_current or "").isdigit()
                else None
            ) or _declared_current_stage(modality_text) or stages[0]["stage"]
            for stage in stages:
                if stage["stage"] == current_stage and not stage.get("event_at") and offer.get("endDate"):
                    stage["event_at"] = _date_value(offer.get("endDate")).isoformat() if _date_value(offer.get("endDate")) else None
            apply_known_stages(prop, stages, current_stage=current_stage)
            prop.auction_modality = "primeira_praca" if current_stage == "first" else "segunda_praca" if current_stage == "second" else "leilao_online"
        return prop

    async def scrape(self) -> list[ScrapedProperty]:
        properties: list[ScrapedProperty] = []
        seen_ids: set[str] = set()
        async with self._build_client() as client:
            page = 1
            total_pages = 1
            while page <= min(total_pages, self.max_pages):
                query = urlencode({"pageNumber": page, "pageSize": self.page_size})
                try:
                    response = await self._get(client, f"{CATEGORY_URL}?{query}")
                    offers, total = self._offers_from_html(response.text)
                    total_pages = max(1, math.ceil(total / self.page_size))
                    for offer in offers:
                        if not self._accept_store(offer):
                            continue
                        prop = self._normalize_offer(offer)
                        if prop and prop.external_id not in seen_ids:
                            seen_ids.add(prop.external_id)
                            properties.append(prop)
                except Exception as error:
                    self.failed_regions.append(f"page:{page}")
                    print(f"[{self.source_id}] Página {page} falhou: {error}")
                page += 1

        if properties and not self.failed_regions:
            self.successful_regions = ["SP"]
        elif not properties:
            self.failed_regions.append("SP")
        print(f"[{self.source_id}] Total São Paulo/SP: {len(properties)} imóveis")
        return properties


class SuperbidSource(_SuperbidMarketplaceSource):
    source_id = "superbid"
    collector_version = "superbid-1.0.0"
    include_sold = False


class SoldSource(_SuperbidMarketplaceSource):
    source_id = "sold"
    collector_version = "sold-1.0.0"
    include_sold = True
